// app/javascript/controllers/index.js

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BgmController from "./bgm_controller"
application.register("bgm", BgmController)

import LobbyController from "./lobby_controller"
application.register("lobby", LobbyController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ResultController from "./result_controller"
application.register("result", ResultController)

import ShiritoriController from "./shiritori_controller"
application.register("shiritori", ShiritoriController)

import WaitingRoomController from "./waiting_room_controller"
application.register("waiting-room", WaitingRoomController)